// <auto-generated />
using System;
using HealthMonitor.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthMonitor.DataAccess.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("HealthMonitor.DataAccess.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HealthMonitor.DataAccess.Entities.EmployeeSensorHistory", b =>
                {
                    b.Property<Guid>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BloodPressure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BodyTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DeviceUId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeUId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gulucose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HeartRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OxygenSaturation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Respiration")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UId");

                    b.HasIndex("EmployeeUId");

                    b.ToTable("EmployeeSensorHisotry");
                });

            modelBuilder.Entity("HealthMonitor.DataAccess.Entities.EmployeeSensorHistory", b =>
                {
                    b.HasOne("HealthMonitor.DataAccess.Entities.EmployeeEntity", "Employee")
                        .WithMany("EmployeeSensorHistory")
                        .HasForeignKey("EmployeeUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HealthMonitor.DataAccess.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("EmployeeSensorHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
